---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Sync code to EC2
  synchronize:
    src: ~/project/backend
    dest: ~/project

- name: Executing node
  shell: |
    cd ~/project/backend/dist
    pm2 start main.js -f
  environment:
    ENVIRONMENT=production
    TYPEORM_CONNECTION=postgres
    TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts
    TYPEORM_HOST=glee.c16a6detkaax.us-west-2.rds.amazonaws.com
    TYPEORM_PORT=5432
    TYPEORM_USERNAME=postgres
    TYPEORM_PASSWORD=password
    TYPEORM_DATABASE=glee