---
- name: Sync code to EC2
  synchronize:
    src: ~/project/backend
    dest: ~/project
- name: Back-end build
  shell: |
    cd ~/project/backend
    npm install
    npm run build
- name: Executing node
  shell: |
    cd ~/project/backend/dist
    pm2 start main.js -f